version: '3.7'

services:
  dev:
    container_name: dev_api
    build:
      context: .
      dockerfile: Dockerfile
      target: development
    volumes:
      - ./:/usr/src/app
      - /usr/src/app/node_modules
    ports:
      - "8080:8080"
      - "30000:9229"
    command: npm run start:debug

  prod:
    container_name: prod_api
    build:
      context: .
      dockerfile: Dockerfile
      target: production
    volumes:
      - ./:/usr/src/app
      - /usr/src/app/node_modules
    ports:
      - "8080:8080"
      - "30000:9229"
    command: npm run start:prod